# Generated by Django 3.0.10 on 2020-09-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('ESTUDIANTE', 'Estudiante'), ('PROFESOR', 'Profesor')], max_length=100, null=True),
        ),
    ]
