# Generated by Django 3.0.10 on 2020-10-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(null=True, upload_to='clases/cursos/fotos', verbose_name='Ícono del curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(verbose_name='Precio al Estudiante')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('estado', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('ACTIVA', 'Activa'), ('TERMINADA', 'Terminada'), ('REPROGRAMADA', 'Reprogramada'), ('CANCELADA', 'Cancelada'), ('REPORTADA', 'Reportada')], max_length=100, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='clases.Curso')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
