# Generated by Django 3.0.10 on 2020-10-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/institucion', verbose_name='Foto de la institucion'),
        ),
    ]
