# Generated by Django 3.0.10 on 2020-10-02 19:39

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='users.Docente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Estudiante', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.ForeignKey(blank=True, help_text='Campo que referencia al nivel académico: Escolar, Preparatoria, Universidad', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Nivel', verbose_name='Nivel'),
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clases.reserva',),
            managers=[
                ('clases', django.db.models.manager.Manager()),
            ],
        ),
    ]
