# Generated by Django 3.0.10 on 2020-10-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_auto_20201005_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='precio',
            new_name='precio_estudiante',
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_docente',
            field=models.FloatField(default=0, verbose_name='Precio al profesor'),
            preserve_default=False,
        ),
    ]
