# Generated by Django 3.0.10 on 2020-10-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_auto_20201006_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='cursos',
            field=models.ManyToManyField(related_name='cursos', to='clases.Curso'),
        ),
    ]
