# Generated by Django 3.0.10 on 2020-10-12 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0005_docente_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tutelados', to='clases.Tutor'),
        ),
    ]
