# Generated by Django 3.0.10 on 2020-10-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0007_auto_20201012_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Terminada', 'Terminada'), ('Reprogramada', 'Reprogramada'), ('Cancelada', 'Cancelada'), ('Reportada', 'Reportada')], default='Pendiente', max_length=100),
        ),
    ]
