# Generated by Django 3.0.10 on 2020-10-13 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0008_auto_20201012_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Si esta activado, se le mostrará a los usuarios este chat')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chats_docente', to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chats_estudiante_o_tutor', to=settings.AUTH_USER_MODEL, verbose_name='Tutor o Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='clases/mensajes/archivos')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del mensaje')),
                ('visto', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='clases.Chat', verbose_name='Chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
