# Generated by Django 3.0.10 on 2020-10-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0009_chat_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='estrellas',
            field=models.PositiveSmallIntegerField(default=5, help_text='Calificación del 1 a 5 estrellas del docente.'),
        ),
    ]
