# Generated by Django 3.0.10 on 2020-10-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0011_reserva_enlace_videollamada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='enlace_videollamada',
            field=models.URLField(max_length=250),
        ),
    ]
