# Generated by Django 3.0.10 on 2020-10-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0012_auto_20201015_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='estudiante',
            name='breve_cv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estrellas',
            field=models.PositiveSmallIntegerField(default=5, help_text='Calificación del 1 a 5 estrellas del docente.'),
        ),
    ]
