# Generated by Django 3.0.10 on 2020-10-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0012_auto_20201015_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='user',
            name='raw_password',
            field=models.CharField(default='asignar d_de_nuevo_la_contraseña', max_length=255, verbose_name='Contraseña sin encriptar'),
            preserve_default=False,
        ),
    ]
