# Generated by Django 3.0.10 on 2020-10-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0012_auto_20201015_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-id']},
        ),
    ]
