# Generated by Django 3.0.10 on 2020-10-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0013_auto_20201018_1219'),
        ('clases', '0013_auto_20201018_1111'),
    ]

    operations = [
    ]
