# Generated by Django 3.0.10 on 2020-10-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0014_merge_20201018_2129'),
        ('clases', '0014_merge_20201018_2149'),
    ]

    operations = [
    ]
