# Generated by Django 3.0.10 on 2020-10-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0015_merge_20201019_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si esta activado, se le mostrará a los usuarios este chat'),
        ),
    ]
