# Generated by Django 3.0.10 on 2020-12-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clases", "0016_auto_20201020_2120"),
    ]

    operations = [
        migrations.DeleteModel(name="Chat"),
        migrations.DeleteModel(name="Mensaje"),
    ]
