# Generated by Django 3.0.10 on 2020-12-09 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0018_chat_chatuser_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_users', to='clases.Chat'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
