# Generated by Django 3.0.10 on 2020-12-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0019_auto_20201209_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='visto',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('VISTO', 'Visto'), ('ENTREGADO', 'Entregado')], default='ENTREGADO', max_length=15, verbose_name='Estado de mensaje'),
        ),
    ]
