# Generated by Django 3.0.10 on 2020-12-17 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0020_auto_20201215_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeVisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('chat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.ChatUser')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Mensaje')),
            ],
            options={
                'unique_together': {('chat_user', 'mensaje')},
            },
        ),
        migrations.AddField(
            model_name='mensaje',
            name='users_visto',
            field=models.ManyToManyField(through='clases.MensajeVisto', to='clases.ChatUser'),
        ),
    ]
