# Generated by Django 3.0.10 on 2020-12-17 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0021_auto_20201216_2008'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatuser',
            unique_together={('user', 'chat')},
        ),
    ]
