# Generated by Django 3.0.10 on 2021-01-08 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0022_auto_20201216_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de pago',
                'verbose_name_plural': 'Tipos de pago',
            },
        ),
        migrations.AddField(
            model_name='mediopago',
            name='dni_destinatario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mediopago',
            name='nombre_destinatario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mediopago',
            name='numero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_docente',
            field=models.FloatField(default=0, verbose_name='Precio al profesor'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_estudiante',
            field=models.FloatField(default=0, verbose_name='Precio al Estudiante'),
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.IntegerField(default=0)),
                ('hora_fin', models.IntegerField(default=0)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_disponibles', to='clases.Dia')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='horario',
            field=models.ManyToManyField(related_name='horario', to='clases.Hora'),
        ),
        migrations.AddField(
            model_name='mediopago',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.TipoPago'),
        ),
    ]
