# Generated by Django 3.0.10 on 2021-01-10 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0023_auto_20210108_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='N° orden de compra'),
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='clases.TipoPago'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_reservas', to='clases.Estudiante', verbose_name='Estudiante'),
        ),
    ]
