# Generated by Django 3.0.10 on 2021-01-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0024_auto_20210109_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='N° Orden de compra'),
        ),
    ]
