# Generated by Django 3.0.10 on 2021-01-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0025_reserva_orden_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('NoPagada', 'No pagada'), ('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Terminada', 'Terminada'), ('Reprogramada', 'Reprogramada'), ('Cancelada', 'Cancelada'), ('Reportada', 'Reportada')], default='Pendiente', max_length=100),
        ),
    ]
