# Generated by Django 3.0.10 on 2021-01-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0026_auto_20210110_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('porcentaje_descuento', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='foto_pago',
            field=models.ImageField(blank=True, null=True, upload_to='clases/pagos/', verbose_name='Foto de pago'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Monto sin descuento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Monto con descuento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='porcentaje_descuento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Porcentaje de descuento(%)'),
        ),
    ]
