# Generated by Django 3.0.10 on 2021-01-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0027_auto_20210110_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigodescuento',
            options={'verbose_name': 'Código de descuento', 'verbose_name_plural': 'Códigos de descuento'},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('NoPagada', 'No pagada'), ('Pagada', 'Pagada'), ('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Terminada', 'Terminada'), ('Reprogramada', 'Reprogramada'), ('Cancelada', 'Cancelada'), ('Reportada', 'Reportada')], default='Pendiente', max_length=100),
        ),
    ]
