# Generated by Django 3.0.10 on 2021-01-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0028_auto_20210110_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediopago',
            name='icono',
            field=models.ImageField(blank=True, help_text="Este ícono solo es visible para los medios de pago de tipo 'Transferencia por celular'", null=True, upload_to='clases/medios_de_pago/', verbose_name='Ícono de medio de pago'),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='clases/tipos_de_pago/', verbose_name='Ícono de tipo de pago'),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='prioridad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='tipo_modal',
            field=models.CharField(blank=True, choices=[('MODAL_TRANSFERENCIA_INTERBANCARIA', 'MODAL TRANSFERENCIA INTERBANCARIA'), ('MODAL_DEPOSITO_BANCARIO', 'MODAL DEPOSITO BANCARIO'), ('MODAL_TRANSFERENCIA_MOVIL', 'MODAL TRANSFERENCIA MÓVIL')], max_length=250, null=True),
        ),
    ]
