# Generated by Django 3.0.10 on 2021-01-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0030_auto_20210113_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='porcentaje_descuento',
        ),
        migrations.AddField(
            model_name='reserva',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
