# Generated by Django 3.0.10 on 2021-01-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0032_auto_20210118_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='observaciones_texto_pago',
            field=models.TextField(blank=True, help_text='Observaciones que se hacen desde la comprobación con OCR', null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado_foto_pago',
            field=models.CharField(choices=[('Evaluada', 'Evaluada'), ('Comprobada', 'Comprobada')], default='Evaluada', max_length=100),
        ),
    ]
