# Generated by Django 3.0.10 on 2020-10-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0013_auto_20201018_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMetricas',
            fields=[
            ],
            options={
                'verbose_name': 'Chat Metricas',
                'verbose_name_plural': 'Chats Metricas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clases.chat',),
        ),
    ]
