# Generated by Django 3.0.10 on 2020-10-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0013_auto_20201018_1111'),
        ('administrar_chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMetricas',
        ),
        migrations.CreateModel(
            name='ChatAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Administración chat',
                'verbose_name_plural': 'Administración chats',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clases.chat',),
        ),
    ]
