# Generated by Django 3.0.10 on 2020-12-09 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administrar_chat", "0002_auto_20201018_1832"),
    ]

    operations = [
        migrations.DeleteModel(name="ChatAdmin"),
    ]
