# Generated by Django 3.0.10 on 2021-01-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0023_auto_20210108_0027'),
        ('administrar_chat', '0003_auto_20201209_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Administración chat',
                'verbose_name_plural': 'Administración chats',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clases.chat',),
        ),
    ]
